apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-ui
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: myapp-ui
  template:
    metadata:
      labels:
        app: myapp-ui
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        name: myapp-ui
        ports:
        - containerPort: 80
