apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-ui
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: static-ui
  template:
    metadata:
      labels:
        app: static-ui
    spec:
      containers:
      - image: dockersamples/static-site
        name: static-ui
        ports:
        - containerPort: 80
